### PR TITLE
fix: remove unnecessary check

### PR DESCRIPTION
**Pull request by unseeyou**
already checked above

### CODE REVIEW

**Comment by aphkyle** [comment]
I would prefer using the checker just only because I personally think it is more readable. but whatever floats the boat!

**Comment by interrrp** [comment]
Same, this looks cleaner:
```py
info_dict = {
    "Joined:": f"<t:{int(member.joined_at.timestamp())}:R>",
    "Roles:": ", ".join(role.mention for role in member.roles[1:]),
    "Tags:": ", ".join(f"`{tag}`" for tag in tag_list),
}

content = "**Member Info**\n"
for key, value in info_dict.items():
    if value != "":
        content += f"{key} {value}\n"
    else:
        content += f"{key} None\n"
```

**Comment by unseeyou** [comment]
Ok someone do that

**Review by aphkyle — APPROVED** [review]
alright time to merge!

**Pull request merged**
